feat(): Added enterprise option
kubeslice/kubeslice-cli pull request #13
Opened 2022-09-12 10:05 UTC by roshanikk

2022-09-13 08:31 UTC, that-backend-guy requested changes
enterprise flag is redundant and should be removed

2022-09-13 08:31 UTC, that-backend-guy commented on cmd/install.go
> +	enterprise bool
do we need the `enterprise bool` flag? We can directly install kubeslice-ui if the chart configuration was provided by the end user. this flag seems redundant

2022-09-13 09:36 UTC, roshanikk commented on cmd/install.go
> +	enterprise bool
Agreed

2022-09-13 11:11 UTC, priyank-upadhyay commented on cmd/install.go
>  	- demo: Skips the installation of additional example applications`)
We can add a skip option for `ui` as well.

2022-09-14 05:05 UTC, priyank-upadhyay approved these changes

2022-09-14 06:03 UTC, merged